config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  resources :short_stories
  resources :poems

  resource :author

end

app/models/author.rb
class Author < ActiveRecord::Base

  model_name.instance_variable_set(:@route_key, 'author')

  has_many :short_stories, :inverse_of => :author
  has_many :poems, :inverse_of => :author
  has_many :publications, :inverse_of => :author

  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggable

  belongs_to :user, :inverse_of => :author


  validates_presence_of :name, :biography

  validate :must_have_user

  private


  def must_have_user
    if user.blank? && user_id.blank?
      self.errors.add(:user, I18n.t("errors.messages.existence"))
    end
  end

end

app/models/poem.rb
class Poem < Publication
  belongs_to :author, :inverse_of => :poems
  
  validate :must_have_author
  validates_presence_of :title, :content, :published_at, :metaphor

  def metaphor
    description
  end

  def metaphor=(description)
    self.description = description
  end

  private

  def must_have_author
    if author.blank? && author_id.blank?
      self.errors.add(:author, I18n.t("errors.messages.existence"))
    end
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author, :inverse_of => :publications

  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  scope :by, lambda {|author| where(:author_id => (author.try(:id) || 0))}

  scope :latest, lambda {order("id desc").limit(10)}


  paginates_per 10

end

app/models/short_story.rb
class ShortStory < Publication
  belongs_to :author, :inverse_of => :short_stories

  validate :must_have_author

  validates_presence_of :title, :content, :description, :published_at

  private

  def must_have_author
    if author.blank? && author_id.blank?
      self.errors.add(:author, I18n.t("errors.messages.existence"))
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  
  has_many :authors, :through => :taggings, :source => :taggable, :source_type => "Author"

  has_many :poems, ->{where(:type => 'Poem')}, :through => :taggings, :source => :taggable, :source_type => "Publication"
  has_many :short_stories, ->{where(:type => 'ShortStory')}, :through => :taggings, :source => :taggable, :source_type => "Publication"

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :author, :inverse_of => :user

  def author_name
    author.try(:name)
  end

  def author_bio
    author.try(:biography)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :authenticate_user!

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.user = current_user
    if @author.save 
      AuthorTaggingService.new(@author).tag!
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @author = current_user.author
  end

  def update
    if current_user.author.update_attributes(author_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private 

  def author_params
    params.require(:author).permit(:name, :biography)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @publications = Publication.latest.preload(:author, :tags).page(params[:page])
  end

  def dashboard
    authenticate_user!
    @poems = Poem.by(current_user.author)
    @short_stories = ShortStory.by(current_user.author)
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @poems = Poem.latest.preload(:author, :tags).page(params[:page])
  end

  def new
    creation_policy_check!
    @poem = Poem.new 
  end

  def create
    return unless creation_policy_check!
    @poem = Poem.new(poem_params)
    @poem.author = current_user.author
    @poem.published_at = Date.today
    if @poem.save
      PoemTaggingService.new(@poem).tag!
      redirect_to poem_path(@poem)
    else
      render :new
    end
  end

  def show
    @poem = Poem.find(params[:id])
  end

  def edit
    @poem = Poem.find(params[:id])
    change_policy_check!(@poem)
  end

  def update
    @poem = Poem.find(params[:id])
    return unless change_policy_check!(@poem)
    if @poem.update_attributes(poem_params)
      redirect_to poem_path(@poem)
    else
      render :edit
    end
  end

  def destroy
  end

  private 

  def creation_policy_check!
    policy = PublicationCreationPolicy.new(current_user)
    if policy.check!
      true
    else
      redirect_to root_path, :notice => policy.message unless policy.check!
      false
    end
  end

  def change_policy_check!(publication)
    policy = PublicationChangePolicy.new(current_user, publication)
    if policy.check!
      true
    else
      redirect_to root_path, :notice => policy.message unless policy.check!
      false
    end
  end

  def poem_params
    params.require(:poem).permit(:title, :content, :metaphor)
  end
end

app/controllers/short_stories_controller.rb
class ShortStoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @short_stories = ShortStory.latest.preload(:author, :tags).page(params[:page])
  end


  def new
    creation_policy_check!
    @short_story = ShortStory.new 
  end

  def create
    return unless creation_policy_check!
    @short_story = ShortStory.new(short_story_params)
    @short_story.author = current_user.author
    @short_story.published_at = Date.today
    if @short_story.save
      ShortStoryTaggingService.new(@short_story).tag!
      redirect_to short_story_path(@short_story)
    else
      render :new
    end
  end

  def show
    @short_story = ShortStory.find(params[:id]) 
  end

  def edit
    @short_story = ShortStory.find(params[:id])
    return unless change_policy_check!(@short_story)
  end

  def update
    @short_story = ShortStory.find(params[:id])
    return unless change_policy_check!(@short_story)
    if @short_story.update_attributes(short_story_params)
      redirect_to short_story_path(@short_story)
    else
      render :edit
    end
  end

  def destroy
  end 


  private 

  def creation_policy_check!
    policy = PublicationCreationPolicy.new(current_user)
    if policy.check!
      true
    else
      redirect_to root_path, :notice => policy.message unless policy.check!
      false
    end
  end

  def change_policy_check!(publication)
    policy = PublicationChangePolicy.new(current_user, publication)
    if policy.check!
      true
    else
      redirect_to root_path, :notice => policy.message unless policy.check!
      false
    end
  end

  def short_story_params
    params.require(:short_story).permit(:title, :content, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def present(object, klass=nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

  def errors_for(obj)
    if obj.errors.any?
      render :partial => 'shared/form_errors', :locals => {:record => obj}
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <%= errors_for(@author) %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :biography %>
    <%= f.text_area :biography, :class => "form-control" %>
  </div>


  <%= f.submit 'Save', :class => 'btn btn-primary' %>

<% end %>

app/views/authors/edit.html.erb
<%= render 'form' %>

app/views/authors/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoetryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Publicity</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Poems', poems_path %></li>
          <li><%= link_to 'Short Stories', short_stories_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Dashboard', dashboard_path %></li>
                <li><%= link_to 'New Poem', new_poem_path %></li>
                <li><%= link_to 'New Story', new_short_story_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %> 
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
  <h3>Author Info</h3> 

  <% if current_user.author %>
    <p>Name: <%= current_user.author_name %></p>
    <p>Bio: <%= current_user.author_bio %></p>
    <%= link_to 'Edit info', edit_author_path %>
  <% else %>
    <%= link_to 'Add info', new_author_path %>
  <% end %>
</div>

<div class="row">
  <h3>Poems</h3>

  <% @poems.each do |poem| %>
    <div class="poem">
      <%= link_to poem.title, poem_path(poem) %>
      <p>
        <%= poem.metaphor %>
      </p>
    </div>
  <% end %>
</div>

<div class="row">
  <h3>Stories</h3>

  <% @short_stories.each do |story| %>
    <div class="story">
      <%= link_to story.title, short_story_path(story) %>
      <p>
        <%= story.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<% @publications.each do |publication| %>
  <% present publication, PublicationPresenter do |p| %>
    <div class="publication">
      <h2><%= p.link_to_page %></h2>
      <p><em>Published on <%= p.published %>  by <%= p.author %> - <%= p.type %></em></p>
      <p><%= p.excerpt %></p>
    </div>
  <% end %>
<% end %>

app/views/poems/_form.html.erb
<%= form_for @poem do |f| %>

  <%= errors_for(@poem) %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :metaphor %>
    <%= f.text_area :metaphor, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => 'form-control' %>
  </div>

  <%= f.submit 'Save', :class => 'btn btn-primary' %>
<% end %>

app/views/poems/index.html.erb
<h2>Poems</h2>

<% @poems.each do |poem| %>
  <% present poem, PublicationPresenter do |p| %>
    <div class="publication">
      <h2><%= p.link_to_page %></h2>
      <p><em>Published on <%= p.published %>  by <%= p.author %> - <%= p.type %></em></p>
      <p><%= p.excerpt %></p>
      <p><%= p.taglist %></p>
    </div>
  <% end %>
<% end %>

<%= paginate @poems %>

app/views/poems/new.html.erb
<%= render 'form' %>

app/views/poems/show.html.erb
<h2><%= @poem.title %></h2>
<p><%= @poem.content %></p>

app/views/shared/_form_errors.html.erb
<div id="error_explanation">
  <h3><%= pluralize(record.errors.count, 'error') %> prevented saving this record</h3>
  <ul>
    <% record.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>

app/views/short_stories/_form.html.erb
<%= form_for @short_story do |f| %>

  <%= errors_for(@short_story) %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Short Description' %>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => 'form-control' %>
  </div>

  <%= f.submit 'Save', :class => 'btn btn-primary' %>
<% end %>

app/views/short_stories/index.html.erb
<h2>Short Stories</h2>

<% @short_stories.each do |short_story| %>
  <% present short_story, PublicationPresenter do |p| %>
    <div class="publication">
      <h2><%= p.link_to_page %></h2>
      <p><em>Published on <%= p.published %>  by <%= p.author %> - <%= p.type %></em></p>
      <p><%= p.excerpt %></p>
      <p><%= p.taglist %></p>
    </div>
  <% end %>
<% end %>

<%= paginate @short_stories %>

app/views/short_stories/new.html.erb
<%= render 'form' %>

app/views/short_stories/show.html.erb
<h2><%= @short_story.title %></h2>
<p><%= @short_story.content %></p>